use dioxus::prelude::*;

use crate::{
    components::ConfigChecklist,
    utils::{TextCommandColor, h3_heading, text_command}
};

#[component]
pub fn Content() -> Element {
    rsx! {
        p {
            "A switch configures its IPv4 address and mask on this special NIC-like VLAN interface."
            br {}
            "The following steps list the commands used to configure IPv4 on a switch, assuming that the IP
            address is configured to be in VLAN 1, with Example 6-7 that follows showing an example
            configuration."
        }
        ConfigChecklist {}
        ol { class: "mb-4",
            // Step 1
            li {
                span { class: "text-sky-500 font-semibold mr-4", "Step 1." }
                "Use the "
                {text_command("interface vlan 1", TextCommandColor::Gold)}
                " command in global configuration mode to enter interface VLAN 1 configuration mode."
            }
            // Step 2
            li {
                span { class: "text-sky-500 font-semibold mr-4", "Step 2." }
                "Use the "
                {text_command("ip address", TextCommandColor::Gold)}
                i { " ip-address mask" }
                " command in interface configuration mode to assign an IP address and mask."
            }
            // Step 3
            li {
                span { class: "text-sky-500 font-semibold mr-4", "Step 3." }
                "Use the "
                {text_command("no shutdown", TextCommandColor::Gold)}
                " command in interface configuration mode to enable the VLAN 1 interface if it is not already enabled."
            }
            // Step 4
            li {
                span { class: "text-sky-500 font-semibold mr-4", "Step 4." }
                "Add the "
                {text_command("ip default-gateway", TextCommandColor::Gold)}
                i { " ip-address" }
                " command in global configuration mode to configure the default gateway."
            }
            // Step 5
            li {
                span { class: "text-sky-500 font-semibold mr-4", "Step 5." }
                "(Optional) Add the "
                {text_command(" ip name-server", TextCommandColor::Gold)}
                i { " ip-address1 ip-address2 …" }
                " command in global configuration mode to configure the switch to use Domain Name System
                (DNS) to resolve names into their matching IP address."
            }
        }

        img {
            class: "mb-4 rounded-lg",
            alt: "Example 6-7 Switch Static IP Address Configuration",
            loading: "lazy",
            src: asset!("/assets/static/v1p2c6s2sh2ex6-7.png", AssetOptions::image().with_avif()),
        }

        {h3_heading("Enabling/Disabling an Interface")}
        p { class: "mb-4",
            "On a side note, this example shows a particularly important and common command: the "
            {text_command("[no] shutdown", TextCommandColor::Gold)}
            " command."
            br {}
            "To administratively enable an interface on a switch, use the "
            {text_command("no shutdown", TextCommandColor::Gold)}
            " interface subcommand; to disable an interface, use the "
            {text_command("shutdown", TextCommandColor::Gold)}
            " interface subcommand."
            br {}
            "This command can be used on the physical Ethernet interfaces that the switch
            uses to switch Ethernet messages in addition to the VLAN interface shown here in this
            example."
        }

        {h3_heading("Syslog Messages")}
        p { class: "mb-4",
            "Also, pause long enough to look at the messages that appear just below the no shutdown
            command in Example 6-7."
            br {}
            "Those messages are syslog messages generated by the switch stating that 
            the switch did indeed enable the interface."
            br {}
            "Switches (and routers) generate syslog messages in response to a variety of events, and by default, 
            those messages appear at the console."
            br {}
            "Chapter 9, “Device Management Protocols,” in the CCNA 200-301 Official Cert
            Guide, Volume 2, discusses syslog messages in more detail."
        }

        {h3_heading("RECAP")}
        ol { class: "list-disc list-inside",
            li {
                "A switch configures its IPv4 address and mask on this special NIC-like VLAN interface."
            }
        }
    }
}